image: docker:20

stages:
  - build
  - deploy

services:
  - docker:dind

Build-Dev:
    stage: build
    only:
        - develop
    script: 
        - echo $MY_CI_REGISTRY_PASSWORD | docker login $MY_CI_REGISTRY --username $MY_CI_REGISTRY_USER --password-stdin
        - docker build --pull --network=host --tag=$MY_CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
        - docker push $MY_CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
        - docker logout

Build-Prd:
    stage: build
    only:
        - main
    script: 
        - echo "hi"
