image: docker:20

stages:
  - build
  - deploy

services:
  - docker:dind

Build-Dev:
    stage: build
    only:
        - develop
    script: 
        - echo "$MY_CI_REGISTRY"
        - echo "$MY_CI_REGISTRY_USER"
        - echo "$MY_CI_REGISTRY_PASSWORD"
        - echo "$MY_CI_REGISTRY_IMAGE"
        - echo "hi"

Build-Prd:
    stage: build
    only:
        - main
    script: 
        - echo "hi"
